# Generated by Django 6.0.5 on 2026-05-23 15:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.listing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="listing_images")),
                ("is_main", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "car_images",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "region",
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("color", models.CharField(max_length=50)),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            apps.listing.models.validate_max_year,
                        ]
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(help_text="Mileage in kilometers"),
                ),
                ("engine_volume", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[("new", "Новий"), ("used", "Вживаний")], max_length=20
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("sedan", "Седан"),
                            ("suv", "Позашляховик"),
                            ("hatchback", "Хетчбек"),
                            ("coupe", "Купе"),
                            ("wagon", "Універсал"),
                            ("pickup", "Пікап"),
                            ("van", "Мінівен"),
                            ("cabrio", "Кабріолет"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Бензин"),
                            ("diesel", "Дизель"),
                            ("hybrid", "Гібрид"),
                            ("electric", "Електричний"),
                            ("gas", "Газ"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transmission_type",
                    models.CharField(
                        choices=[
                            ("manual", "Механіка"),
                            ("automatic", "Автомат"),
                            ("robot", "Робот"),
                            ("cvt", "Варіатор"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        choices=[
                            ("fwd", "Передній привід"),
                            ("rwd", "Задній привід"),
                            ("awd", "Повний привід"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "Долар США"),
                            ("EUR", "Євро"),
                            ("UAH", "Гривня"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_eur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_uah",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "exchange_rate_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "exchange_rate_eur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "listing_status",
                    models.CharField(
                        choices=[
                            ("active", "Активне"),
                            ("pending", "На перевірці"),
                            ("rejected", "Відхилено"),
                            ("blocked", "Заблоковано"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("edit_count", models.PositiveIntegerField(default=0)),
                ("moderation_count", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="cars.carmodel",
                    ),
                ),
            ],
            options={
                "db_table": "listing",
            },
        ),
    ]
