# Generated by Django 6.0.6 on 2026-06-27 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="carimage",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_images",
                to="listing.listing",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="listing.region",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["price_usd"], name="listing_price_usd_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["price_eur"], name="listing_price_eur_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["price_uah"], name="listing_price_uah_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["year"], name="listing_year_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["status"], name="listing_status_idx"),
        ),
    ]
