# Generated by Django 6.0.5 on 2026-07-05 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0002_initial"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="exchange_rate_eur",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="exchange_rate_usd",
        ),
        migrations.AddField(
            model_name="listing",
            name="exchange_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.currencyrate",
            ),
        ),
    ]
