# Generated by Django 6.0.5 on 2026-07-28 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0003_remove_listing_exchange_rate_eur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listings",
                to="listing.region",
            ),
        ),
    ]
