# Generated by Django 6.0.7 on 2026-07-28 08:45

from django.db import migrations, models

import apps.core.services.upload_image


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0004_alter_listing_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carimage",
            name="image",
            field=models.ImageField(
                upload_to=apps.core.services.upload_image.upload_listing_image
            ),
        ),
    ]
