# Generated by Django 6.0.8 on 2026-08-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0005_alter_carimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="mileage",
            field=models.PositiveIntegerField(help_text="Пробіг у кілометрах"),
        ),
    ]
