# Generated by Django 6.0.6 on 2026-06-27 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listing_stats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listingstats",
            name="viewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="listingstats",
            index=models.Index(
                fields=["created_at"], name="listing_sta_created_1f5626_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingstats",
            index=models.Index(
                fields=["listing"], name="listing_sta_listing_21d5a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingstats",
            index=models.Index(
                fields=["listing", "created_at"], name="listing_sta_listing_de4b1b_idx"
            ),
        ),
    ]
