# Generated by Django 6.0.7 on 2026-08-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listing_stats", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listingstats",
            options={},
        ),
    ]
