# Generated by Django 6.0.5 on 2026-05-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="carmodel",
            options={"ordering": ["id"]},
        ),
    ]
