# Generated by Django 6.0.6 on 2026-06-27 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingModeration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "moderation_action",
                    models.CharField(
                        choices=[
                            ("created", "Створено"),
                            ("edited", "Відредаговано продавцем"),
                            ("auto_approved", "Автоматично схвалено"),
                            ("auto_rejected", "Автоматично відхилено"),
                            ("manual_approved", "Схвалено менеджером"),
                            ("manual_rejected", "Відхилено менеджером"),
                        ],
                        max_length=20,
                    ),
                ),
                ("send_letter_at", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="listing.listing",
                    ),
                ),
            ],
            options={
                "db_table": "listing_moderation",
                "ordering": ["id"],
            },
        ),
    ]
