# Generated by Django 6.0.5 on 2026-05-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listingmoderation",
            options={"ordering": ["id"]},
        ),
    ]
