# Generated by Django 6.0.7 on 2026-08-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listingmoderation",
            options={"ordering": ["-created_at"]},
        ),
    ]
