# Generated by Django 6.0.5 on 2026-05-27 15:36

from django.db import migrations


# функції створення та видалення ролей
def create_roles(apps, schema_editor):
    # Отримуємо модель Role
    Role = apps.get_model('users', 'Role')

    # Список ролей
    default_roles = ['buyer', 'seller', 'manager', 'admin']

    for role_name in default_roles:
        #роль створиться, тільки якщо її ще немає
        Role.objects.get_or_create(name=role_name)


def remove_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Role.objects.filter(name__in=['buyer', 'seller', 'manager', 'admin']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options"),
    ]
    operations = [
        migrations.RunPython(create_roles, reverse_code=remove_roles),
    ]