# Generated by Django 6.0.7 on 2026-07-28 08:50

from django.db import migrations, models

import apps.core.services.upload_image


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_seed_roles_and_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.core.services.upload_image.upload_profile_logo,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.core.services.upload_image.upload_avatar,
            ),
        ),
    ]
