# Generated by Django 6.0.5 on 2026-05-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_profile_phone_user_deleted_at_and_more"),
        ("users", "0005_create_permissions"),
    ]

    operations = []
